name: Go Application In-Depth User Scenario Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-docker@v2
      with:
        dockerfile: Dockerfile  # Specify the path to your Dockerfile

    - name: Build Docker image
      run: docker build -t goapp .

    - name: Run Docker container
      run: docker run -d --name goapp -p 8000:8000 goapp

    - name: Wait for container to start
      run: sleep 10

    - name: Run API Tests
      run: |
        bash api_tests.sh

    - name: Stop Docker container
      run: docker stop goapp
