name: Go Application In-Depth User Scenario Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: gedeonkoumako/goapp:latest

      - name: Run API Tests
        run: |
          timeout 10m bash api_tests.sh
          if [ $? -ne 0 ]; then
            echo "API tests failed."
            exit 1
          fi

      - name: Stop and Remove Docker container
        run: |
          docker stop goapp
          docker rm goapp
